# Generated by Django 5.2.8 on 2025-11-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('college', models.CharField(max_length=100, verbose_name='学院')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
    ]
